<img src="https://i.imgur.com/nTOFzVI.png" alt="drawing" width="400"/>

# by One Fourth Labs


For more reading refer official reference of Numpy https://numpy.org/doc/stable/user/quickstart.html


In [ ]:
import numpy as np

## Comparing performance with lists, etc.

In [ ]:
N = 100000000

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 22.3 s, sys: 2.04 s, total: 24.3 s
Wall time: 24.6 s


In [ ]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 9.09 s, sys: 4.51 s, total: 13.6 s
Wall time: 13.6 s


In [ ]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

CPU times: user 2.39 s, sys: 1.47 s, total: 3.86 s
Wall time: 3.86 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

CPU times: user 12.2 s, sys: 1.48 s, total: 13.7 s
Wall time: 13.7 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 2.95 s, sys: 1.44 s, total: 4.39 s
Wall time: 4.4 s


In [ ]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 364 ms, sys: 29.9 ms, total: 394 ms
Wall time: 402 ms


In [ ]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 252 ms, sys: 13 ms, total: 265 ms
Wall time: 265 ms


# Creating np Arrays

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([0.0, 2, 4, 6, 8])

In [ ]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [ ]:
arr

array([0., 2., 4., 6., 8.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
arr.itemsize

8

In [ ]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.size

6

In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.size

12

In [ ]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [ ]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.58768996,  0.10474105, -0.04881658],
       [ 0.16805894,  0.41714503, -0.81174963]])

In [ ]:
np.random.rand(2, 3)

array([[0.90978303, 0.67518903, 0.20384278],
       [0.17316464, 0.56745283, 0.2641691 ]])

In [ ]:
np.random.rand(10, 1)

array([[0.54903648],
       [0.40555604],
       [0.53685451],
       [0.69333717],
       [0.07629448],
       [0.9653904 ],
       [0.39678167],
       [0.94247879],
       [0.27448235],
       [0.77496616]])

In [ ]:
np.random.randint(0, 100, (2, 3))

array([[53, 20, 38],
       [65, 42, 33]])

In [ ]:
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [ ]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [ ]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [ ]:
str_arr = np.array(['1.4', '2.1', '1.1'])

In [ ]:
arr = np.array(str_arr, dtype='float')

In [ ]:
arr

array([1.4, 2.1, 1.1])

## indexing

In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [ ]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3d[0, 0, 0]

1

In [ ]:
arr3d[1, 0, 2]

9

In [ ]:
i = 1
j = 0
k = 2
arr3d[i, j, k]

9

In [ ]:
arr3d[1, :, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [ ]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [ ]:
arr_slice = arr3d[:, :, 0:2]

In [ ]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [ ]:
arr_slice.ndim

3

In [ ]:
arr_slice.shape

(2, 2, 2)

In [ ]:
arr_slice[0, 0, 1]

2

In [ ]:
arr_slice[0, 0, 0] = 1729

In [ ]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [ ]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [ ]:
arr_slice[0, 0, 0] = 1

In [ ]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr = np.random.randint(0, 10, (5))

In [ ]:
arr

array([0, 7, 2, 9, 1])

In [ ]:
my_indices = [1, 3, 4]

In [ ]:
arr[my_indices]

array([7, 9, 1])

# Numpy Operations

In [ ]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [ ]:
arr1

array([[0.78854751, 0.70360558, 0.58811947, 0.32484687],
       [0.4895381 , 0.62269457, 0.33200135, 0.9013478 ],
       [0.46561124, 0.40065009, 0.59415011, 0.81294339]])

In [ ]:
arr2

array([[0.31928384, 0.91910597, 0.45253699, 0.70849138],
       [0.18198589, 0.45418381, 0.96828313, 0.11511807],
       [0.83677645, 0.68553264, 0.88054629, 0.28740519]])

In [ ]:
arr1 + arr2

array([[1.10783134, 1.62271155, 1.04065646, 1.03333826],
       [0.67152398, 1.07687838, 1.30028448, 1.01646587],
       [1.30238769, 1.08618273, 1.47469639, 1.10034858]])

In [ ]:
arr1 - arr2

array([[ 0.46926367, -0.2155004 ,  0.13558248, -0.38364451],
       [ 0.30755221,  0.16851076, -0.63628178,  0.78622973],
       [-0.37116522, -0.28488256, -0.28639618,  0.5255382 ]])

In [ ]:
arr1 * arr2

array([[0.25177047, 0.64668808, 0.26614581, 0.23015121],
       [0.08908902, 0.28281779, 0.3214713 , 0.10376142],
       [0.38961252, 0.27465871, 0.52317667, 0.23364415]])

In [ ]:
arr1 / arr2

array([[2.46973825, 0.76553259, 1.29960529, 0.45850505],
       [2.68997834, 1.37101887, 0.34287631, 7.82976809],
       [0.55643444, 0.58443619, 0.67475171, 2.82856197]])

In [ ]:
np.exp(arr1)

array([[2.20019833, 2.02102655, 1.80059914, 1.38381873],
       [1.63156242, 1.86394381, 1.39375473, 2.46292039],
       [1.59298758, 1.49279483, 1.81149072, 2.2545342 ]])

In [ ]:
np.log(np.exp(arr1))

array([[0.78854751, 0.70360558, 0.58811947, 0.32484687],
       [0.4895381 , 0.62269457, 0.33200135, 0.9013478 ],
       [0.46561124, 0.40065009, 0.59415011, 0.81294339]])

In [ ]:
np.sin(arr1)

array([[0.70933019, 0.64697119, 0.55479743, 0.31916367],
       [0.47021828, 0.5832261 , 0.32593574, 0.784164  ],
       [0.44896905, 0.39001703, 0.55980472, 0.72631349]])

In [ ]:
np.cos(arr1)

array([[0.70487636, 0.76251445, 0.83198546, 0.94769961],
       [0.88255015, 0.81230986, 0.94539193, 0.62055364],
       [0.89354731, 0.92080764, 0.82862457, 0.68736359]])

In [ ]:
np.sqrt(arr1)

array([[0.88800197, 0.838812  , 0.76688947, 0.5699534 ],
       [0.69966999, 0.78910999, 0.57619558, 0.94939338],
       [0.68235712, 0.63296926, 0.77081133, 0.90163373]])

In [ ]:
arr_inv = 1 / arr1

In [ ]:
arr_inv

array([[1.26815441, 1.42125082, 1.70033481, 3.07837347],
       [2.04274194, 1.60592375, 3.01203596, 1.10944965],
       [2.14771449, 2.49594354, 1.68307635, 1.23009796]])

In [ ]:
arr1 = np.zeros((3, 5))

In [ ]:
arr_inv = 1/arr1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [ ]:
np.isinf(arr_inv[0,0])

True

In [ ]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Broadcasting

In [ ]:
arr1 = np.arange(6)

In [ ]:
arr1.shape

(6,)

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1 = arr1.reshape((3, 2))

In [ ]:
arr1.shape

(3, 2)

In [ ]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2 = np.arange(6).reshape((3, 2))

In [ ]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arr2[0].reshape((1, 2))

array([[0, 1]])

In [ ]:
arr1 + arr2[0].reshape((1, 2)) # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [ ]:
arr2[:, 0].reshape((3, 1))

array([[0],
       [2],
       [4]])

In [ ]:
arr1 + arr2[:, 0].reshape((3, 1)) # (3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr1 = np.arange(24).reshape((2, 3, 4))

In [ ]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr2 = np.ones((1, 4))

In [ ]:
arr1 + arr2   # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [ ]:
arr1 = np.arange(4)

In [ ]:
arr2 = np.arange(5)

In [ ]:
print(arr1.shape, arr2.shape)

(4,) (5,)


In [ ]:
arr1 + arr2

ValueError: ignored

In [ ]:
arr1.reshape(4, 1) + arr2  # (4, 1) + (5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr = np.random.rand(3, 3)

In [ ]:
arr

array([[0.13825404, 0.03231461, 0.57981765],
       [0.1494115 , 0.08173225, 0.33632277],
       [0.53993937, 0.84939136, 0.31404205]])

In [ ]:
arr.T

array([[0.13825404, 0.1494115 , 0.53993937],
       [0.03231461, 0.08173225, 0.84939136],
       [0.57981765, 0.33632277, 0.31404205]])

# File handling

In [ ]:
planets_small = np.loadtxt("planets_small.txt")

ValueError: ignored

In [ ]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1)

ValueError: ignored

In [ ]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [ ]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [ ]:
planets_small.shape

(3, 9)

In [ ]:
planets = np.loadtxt("planets.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

ValueError: ignored

In [ ]:
planets = np.genfromtxt("planets.txt", 
                        skip_header=1, 
                        usecols = [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
planets.shape

(20, 9)

In [ ]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [ ]:
planets_new = np.nan_to_num(planets, nan=-1)

In [ ]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
np.savetxt('planets_new.txt', planets_new, 
           delimiter=',')

In [ ]:
np.save("planets_new", planets_new)

In [ ]:
!ls -lh

total 24K
-rw-r--r-- 1 root root 1.6K Jan 28 07:40 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jan 28 07:40 planets_new.txt
-rw-r--r-- 1 root root  254 Jan 28 07:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Jan 28 07:40 planets.txt
drwxr-xr-x 1 root root 4.0K Jan 20 17:27 sample_data


In [ ]:
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [ ]:
np.savez("many_arrs", arr1, arr2, arr3)

In [ ]:
!ls -lh

total 1.8M
-rw-r--r-- 1 root root 1.7M Jan 28 07:40 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Jan 28 07:40 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jan 28 07:40 planets_new.txt
-rw-r--r-- 1 root root  254 Jan 28 07:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Jan 28 07:40 planets.txt
drwxr-xr-x 1 root root 4.0K Jan 20 17:27 sample_data


In [ ]:
arrs = np.load('many_arrs.npz')

In [ ]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [ ]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [ ]:
arrs['arr_0'].shape

(1000, 10)

In [ ]:
np.savez_compressed('many_arrs_compressed', 
                    arr1, arr2, arr3)

In [ ]:
!ls -lh

total 3.3M
-rw-r--r-- 1 root root 1.6M Jan 28 07:40 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Jan 28 07:40 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Jan 28 07:40 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jan 28 07:40 planets_new.txt
-rw-r--r-- 1 root root  254 Jan 28 07:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Jan 28 07:40 planets.txt
drwxr-xr-x 1 root root 4.0K Jan 20 17:27 sample_data


In [ ]:
arr1 = np.zeros((10000, 10000))

In [ ]:
np.savez("zeros", arr1)

In [ ]:
np.savez_compressed("zeros_compressed", arr1)

In [ ]:
!ls -lh

total 767M
-rw-r--r-- 1 root root 1.6M Jan 28 07:40 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Jan 28 07:40 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Jan 28 07:40 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jan 28 07:40 planets_new.txt
-rw-r--r-- 1 root root  254 Jan 28 07:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Jan 28 07:40 planets.txt
drwxr-xr-x 1 root root 4.0K Jan 20 17:27 sample_data
-rw-r--r-- 1 root root 760K Jan 28 07:41 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Jan 28 07:40 zeros.npz


# Stats with NumPy

In [ ]:
arr = np.random.rand(10000000,)

In [ ]:
np.amin(arr)

1.9022612818275775e-08

In [ ]:
np.amax(arr)

0.9999999716070386

In [ ]:
np.mean(arr)

0.4999919177198353

In [ ]:
np.var(arr)

0.08335040308316295

In [ ]:
np.std(arr)

0.28870469875490934

In [ ]:
np.median(arr)

0.5000596956100258

In [ ]:
np.percentile(arr, 50)

0.5000596956100258

In [ ]:
np.percentile(arr, 10)

0.09999015790256766

In [ ]:
np.percentile(arr, 90)

0.9000815577828921

In [ ]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

CPU times: user 312 ms, sys: 22.8 ms, total: 334 ms
Wall time: 338 ms


In [ ]:
print(iqr)

0.5000250053597051


In [ ]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

CPU times: user 218 ms, sys: 9.83 ms, total: 228 ms
Wall time: 229 ms


In [ ]:
print(quartiles)

[0.24994135 0.74996636]


In [ ]:
print(iqr)

0.5000250053597051


In [ ]:
(arr - np.mean(arr))/np.std(arr)

array([1.3953378 , 1.55811402, 0.6807386 , ..., 0.11279645, 0.19159941,
       0.14672662])

In [ ]:
np.histogram(arr)

(array([1000095,  999963, 1001651,  998355,  999374,  999758, 1000584,
        1000603,  998832, 1000785]),
 array([1.90226128e-08, 1.00000014e-01, 2.00000010e-01, 3.00000005e-01,
        4.00000000e-01, 4.99999995e-01, 5.99999991e-01, 6.99999986e-01,
        7.99999981e-01, 8.99999976e-01, 9.99999972e-01]))

In [ ]:
np.histogram(arr, bins=5)

(array([2000058, 2000006, 1999132, 2001187, 1999617]),
 array([1.90226128e-08, 2.00000010e-01, 4.00000000e-01, 5.99999991e-01,
        7.99999981e-01, 9.99999972e-01]))

In [ ]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([2500619, 2498819, 2500899, 2499663]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [ ]:
np.digitize(arr, bins)

array([4, 4, 3, ..., 3, 3, 3])

In [ ]:
arr1 = np.random.randint(0, 10, (10))

In [ ]:
arr1

array([6, 7, 8, 5, 5, 1, 7, 6, 4, 4])

In [ ]:
bins = [0, 6, 10]

In [ ]:
np.digitize(arr1, bins)

array([2, 2, 2, 1, 1, 1, 2, 2, 1, 1])

In [ ]:
np.digitize(arr1, bins, right=True)

array([1, 2, 2, 1, 1, 1, 2, 1, 1, 1])

In [ ]:
arr1 = np.random.randint(50, 80, 100) # weight

In [ ]:
arr2 = np.random.randint(150, 185, 100) # heights

In [ ]:
arr3 = np.random.randint(17, 22, 100) # age

In [ ]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [ ]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [ ]:
arr2d = np.vstack((arr1, arr2, arr3))

In [ ]:
np.amin(arr2d, axis=1)

array([ 50, 150,  17])

In [ ]:
np.amax(arr2d, axis=1)

array([ 79, 184,  21])

In [ ]:
np.mean(arr2d, axis=1)

array([ 65.09, 166.73,  18.88])

# Checking stats rules with numpy

## Mean subracted array has zero mean

In [ ]:
arr = np.random.rand(1000)

In [ ]:
mean = np.mean(arr)

In [ ]:
arr1 = arr - mean

In [ ]:
np.mean(arr1)

6.217248937900877e-18

## Computing mean with smaller set of values

In [ ]:
arr = np.random.rand(1000)

In [ ]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

1 0.8976992538130603
2 0.4729117163929246
3 0.4112364597931963
4 0.5421849824858089
5 0.5310225336122459
6 0.5025103052658842
7 0.45272023237769937
8 0.42642322934175386
9 0.3878759814211546
10 0.44587037747716096
11 0.4732021991014912
12 0.4837831896169132
13 0.47674651533607065
14 0.4991117909414256
15 0.5231819598148638
16 0.5272831066139304
17 0.5067701283783561
18 0.4893100400368103
19 0.4710909564936656
20 0.4735133008478466
21 0.4750750726141005
22 0.4927748632583867
23 0.4846807254948181
24 0.48044648501138615
25 0.4761727764066269
26 0.46359914993072415
27 0.4546977358801244
28 0.4671240791149528
29 0.4607332279992469
30 0.4524201294221584
31 0.45453236581369105
32 0.46969731348073634
33 0.4564554636452928
34 0.4524518884988622
35 0.45773796807291406
36 0.45667357669818975
37 0.4690351099822155
38 0.47065262272011377
39 0.46690603176416445
40 0.46691752972231565
41 0.460042118937319
42 0.45466740144392404
43 0.4594724707311934
44 0.4622336069045428
45 0.45989070284489314
46 0.

In [ ]:
np.cumsum?

In [ ]:
means = np.cumsum(arr)/np.arange(1,1001)

In [ ]:
means[0:15]

array([0.89769925, 0.47291172, 0.41123646, 0.54218498, 0.53102253,
       0.50251031, 0.45272023, 0.42642323, 0.38787598, 0.44587038,
       0.4732022 , 0.48378319, 0.47674652, 0.49911179, 0.52318196])

## Effect of outliers on mean and median

In [ ]:
arr = np.random.randint(1, 100, 100)

In [ ]:
np.mean(arr)

48.27

In [ ]:
np.median(arr)

47.5

In [ ]:
arr = np.append(arr, [1000, 2000])

In [ ]:
arr.shape

(102,)

In [ ]:
np.mean(arr)

76.73529411764706

In [ ]:
np.median(arr)

48.0

## Effect of scaling arrays on mean and median

In [ ]:
arr = np.random.rand(100)

In [ ]:
np.mean(arr)

0.49358647508148223

In [ ]:
np.median(arr)

0.5215359453958905

In [ ]:
arr1 = 2.5 * arr + 0.65

In [ ]:
print(np.mean(2.5 * arr + 0.65), 
      2.5 * np.mean(arr) + 0.65)

1.883966187703706 1.8839661877037055


In [ ]:
print(np.median(2.5 * arr + 0.65), 
      2.5 * np.median(arr) + 0.65)

1.9538398634897265 1.9538398634897263


In [ ]:
print(np.var(2.5 * arr + 0.65), 
      2.5*2.5*np.var(arr))

0.5037909757453505 0.5037909757453506


In [ ]:
print(np.std(2.5 * arr + 0.65), 
      2.5 * np.std(arr))

0.7097823439233681 0.7097823439233684


In [ ]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [ ]:
print( np.mean(0.21 * arr1 - 0.75 * arr2), 
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.2652868483553411 -0.2652868483553411
